package main

const (
	ERRMSG_AUTHENTICATECONNECTION    = "authenticate connection"
	ERRMSG_DEVICECHECK               = "check device/senders.txt for existing device by name"
	ERRMSG_DEVICEOFFLINE             = "device offline"
	ERRMSG_BASEDIR_NOT_FOUND         = "could not find base working directory. device table potentially not initialized"
	ERRMSG_CHANNEL_OPERATION         = "channel operatoin"
	ERRMSG_CONSENT_TO_SEND           = "consent-to-send error"
	ERRMSG_CREATE_DEVICE             = "create device"
	ERRMSG_DB_CONNECTION             = "initiate MySQL database connection"
	ERRMSG_FILEIO                    = "Create/Change File/Directory:\tdeviceauth.go"
	ERRMSG_GETWD                     = "Get Current Working Directory:\tdeviceauth.go"
	ERRMSG_IO                        = "IO operation"
	ERRMSG_JSON_MARSHALL             = "marshal JSON"
	ERRMSG_JSON_UNMARSHALL           = "unmarshal JSON"
	ERRMSG_NETWORK_DIAL              = "dial network connection"
	ERRMSG_NETWORK_CONNECTION        = "new network connection"
	ERRMSG_NETWORK_CONNECTION_CLIENT = "new client connection"
	ERRMSG_NETWORK_SEND_LEN0         = "attempted send of length 0"
	ERRMSG_NETWORK_SEND_TOOSHORT     = "attempted to send message too short for function"
	ERRMSG_NETWORK_READ              = "network connection read"
	ERRMSG_NETWORK_RECEIVE_STRUCT    = "network receive struct"
	ERRMSG_NETWORK_SEND_STRUCT       = "network send struct"
	ERRMSG_NETWORK_WRITE             = "network connection write"
	ERRMSG_NILPTR                    = "nil pointer"
	ERRMSG_READCONN                  = "read connection"
	ERRMSG_READ                      = "read"
	ERRMSG_REGISTER_DEVICE           = "Register device"
	ERRMSG_SELFSEND                  = "check for self-send"
	ERRMSG_TCPLISTENER               = "create TCPListener"
	ERRMSG_WRITE                     = "write"
	ERRMSG_ZEROLENGTH                = "message with zero length"
)
